Screen share implementation
100mslive/100ms-flutter pull request #323
Opened 2021-12-22 15:50 UTC by jashan1498

2022-01-05 01:29 UTC, govindmaheshwari2 approved these changes

2022-01-12 06:20 UTC, ygit commented
@jashan1498 can you resolve the conflicts?

2022-01-17 12:16 UTC, ygit requested changes

2022-01-17 12:16 UTC, ygit commented on android/src/main/kotlin/live/hms/hmssdk_flutter/Constants.kt
> +}
always add an empty line to the end of files

2022-01-17 12:16 UTC, ygit commented on android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
> +            "is_screen_share_active" -> {
all screenshare related cases should be together, below one another
`is_screen_share_active` case should be around `start_screen_share` & `stop_screen_share`

2022-01-17 12:16 UTC, ygit commented on android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
> +    private fun startScreenShare() {
`startScreenShare` function should return `result.success(nil)` if successful or exception hashmap on error

2022-01-17 12:16 UTC, ygit commented on android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
> +        hmssdk.startScreenshare(object : HMSActionResultListener {
should return `result.success(nil)` if successful or exception hashmap on error
use the existing result action listener

2022-01-17 12:16 UTC, ygit commented on example/lib/meeting/hms_sdk_interactor.dart
> +  void startScreenShare() {
should have a action result listener

2022-01-17 12:16 UTC, ygit commented on example/lib/meeting/meeting_store.dart
> +  void startScreenShare() {
should have a action result listener

2022-01-17 12:16 UTC, ygit commented on lib/src/common/platform_methods.dart
> +      case PlatformMethod.isScreenShareActive:
all new API cases should be added to the end.

2022-01-17 12:16 UTC, ygit commented on lib/src/common/platform_methods.dart
> +      case PlatformMethod.startScreenShare:
all new API cases should be added to the end.

2022-01-17 12:16 UTC, ygit commented on lib/src/common/platform_methods.dart
> +        return PlatformMethod.isScreenShareActive;
all new API cases should be added to the end.

2022-01-17 12:16 UTC, ygit commented on lib/src/hmssdk.dart
> +  Future<void> startScreenShare() async {
should be a void function with action result listener

2022-01-17 12:16 UTC, ygit commented on lib/src/hmssdk.dart
> +  Future<void> stopScreenShare() async {
should be a void function with action result listener

2022-01-17 12:16 UTC, ygit commented on pubspec.lock
> +    version: "2.8.1"
don't downgrade the pubspec dependencies

2022-01-20 11:28 UTC, merged